apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
      - name: banking-app
        image: zyange/app-code:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bank-app
spec:
  type: LoadBalancer
  selector:
    app: banking-app
  ports:
  - port: 80
    targetPort: 8080
