apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
      - name: {{ .Values.db.name }}
        image: "{{ .Values.db.image.repository }}:{{.Values.db.image.tag }}"
        ports:
        - containerPort: {{ .Values.db.service.port }}
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.db.name }}
        - name: POSTGRES_DB
          value: {{ .Values.db.config.POSTGRES_DB }}
        - name: POSTGRES_USER
          value: {{ .Values.db.config.POSTGRES_USER }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bank-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.db.name }}-pvc
      - name: init-scripts
        configMap:
          name: {{ .Values.db.name }}-init


