apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.name }}-pv
spec:
  capacity:
    storage: {{ .Values.db.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.db.storage.storageClass }}
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu-worker
