apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bank-db-pvc
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: banking-app
    meta.helm.sh/release-namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
