apiVersion: v1
kind: Secret
metadata:
  name: bank-db-secret
  labels:
    app.kubernetes.io/managed-by: Helm
  annotaions:
    meta.helm.sh/release-name: banking-app
    meta.helm.sh/release-namespace: default
type: Opaque
data:
  DB_PASSWORD: enlhbmdlZTExMjlA		# echo -n 'zyangee1129@' | base64
  DB_USER: YmFua3VzZXI=			# echo -n 'bankuser' | base64
  DB_NAME: YmFuaw==			# echo -n 'bank' | base64
  DB_ROOT_PASSWORD: QmFua3VzZXIhQA==	# echo -n 'Bankuser!@' | base64
