apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zyangee/Ops-repo.git
    targetRevision: HEAD
    path: banking-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
