apiVersion: v1
kind: Secret
metadata:
  name: bank-secrets
type: Opaque
data:
  DB_PASSWORD: {{ .Values.common.secret.DB_PASSWORD | b64enc }}
  JWT_SECRET: {{ .Values.common.secret.JWT_SECRET | b64enc }}
