apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.login.name }}
spec:
  replicas: {{ .Values.login.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.login.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.login.name }}
    spec: 
      containers:
      - name: {{ .Values.login.name }}
        image: "{{ .Values.login.image.repository }}:{{ .Values.login.image.tag }}"
        ports:
        - containerPort: {{ .Values.login.service.port }}
        env:
        - name: MYSQL_HOST
          value: {{ .Values.db.name }}
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: bank-db-secret
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: bank-db-secret
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bank-db-secret
              key: DB_PASSWORD
