global:
  environment: production
  domain: banking-app.zyangee.store

loans:
  name: app-code-loans
  image:
    repository: zyange/app-code-loans
    tag: latest
    platform: linux/arm64
  replicas: 2
  service:
    type: ClusterIP
    port: 8081
  ingress:
    enabled: true
    path: /loans

account:
  name: app-code-account
  image:
    repository: zyange/app-code-account
    tag: latest
    platform: linux/arm64
  replicas: 2
  service:
    type: ClusterIP
    port: 8082
  ingress:
    enabled: true
    path: /account

login: 
  name: app-code-login
  image:
    repository: zyange/app-code-login
    tag: latest
    platform: linux/arm64
  replicas: 2
  service:
    type: ClusterIP
    port: 8083
  ingress:
    enabled: true
    path: /login

db:
  name: bank-db
  image:
    repository: mysql
    tag: "8.0"
    platform: linux/arm64
  storage:
    size: 10Gi
    storageClass: standard
  service:
    type: ClusterIP
    port: 3306
  initdb:
    enabled: true
    scripts:
      - create-tables.sql
      - initial-data.sql
